export const data4 = [
  {
    id: 151,
    question: "Сұрақтың дұрыс нұсқасын табыңыз   What is this woman",
    key: "she is a teacher",
    choices: [
      "she is a teacher",
      "she is beautiful",
      "she has a family",
      "her name is Helen",
      "she has a book",
    ],
  },
  {
    id: 152,
    question: "Дұрыс нұсқасын табыңыз    What is Big Ben",
    key: "clock",
    choices: ["clock", "monument", "theatre", "museum", "cenema"],
  },
  {
    id: 153,
    question: "Дұрыс нұсқаны табыңыз    twenty + twenty-five = ",
    key: "forty-five",
    choices: ["forty-five", "thirty-five", "seventy-five", "fifty-five", "fourty seven"],
  },
  {
    id: 154,
    question: "Дұрыс нұсқасын табыңыз  I have just ______my sister's sun-glasses",
    key: "broken",
    choices: ["broken", "broke", "break", "ate", "breaks"],
  },
  {
    id: 155,
    question: "Дұрыс нұсқасын табыңыз   The capital of the USA is_______",
    key: "Washington",
    choices: ["Washington", "London", "Philadelphia", "New York", "Canada"],
  },
  {
    id: 156,
    question: "Дұрыс нұсқасын табыңыз   17759",
    key: "seventeen thousand seven hundred and fifty nine",
    choices: [
      "seventeen thousand seven hundred and fifty nine",
      "seventeens thousand seven hundred fifty nine",
      "seventeen thousand seventy hundred fifty nine",
      "seventeen thousands seven hundred fifties nine",
      "seven thousands seven hundred fifties nine",
    ],
  },
  {
    id: 157,
    question: "Дұрыс баламасын табыңыз  ______________     No, she's out",
    key: "Is your mother at home",
    choices: [
      "Is your mother at home",
      "Is at home your mother",
      "Does your mother at home",
      "Your mother is at home",
      "Where are yoyr mother",
    ],
  },
  {
    id: 158,
    question: "Салыстырмалы дәрежеде er  жұрнағы жалғанатын үстеуді табыңыз ",
    key: "early",
    choices: ["early", "often", "sometimes", "seldom", "usually"],
  },
  {
    id: 159,
    question: "Сәйкес сын есімді пайдаланып сөйлемді аяқтаңыз  What's_______river in the world",
    key: "the longest",
    choices: ["the longest", "the longer", "longest", "longer", "long"],
  },
  {
    id: 160,
    question: "Етістіктің дұрыс нұсқасын табыңыз     Yesterday morning Helen_______at 7 o'clock",
    key: "woke up",
    choices: ["woke up", "will wake up", "is waking up", "wake up", "wade"],
  },
  {
    id: 161,
    question: "Дұрыс нұсқасын табыңыз   There are 584 students at the department",
    key: " Five hundred and eighty-four",
    choices: [
      " Five hundred and eighty-four",
      " Five eighty-four hundred",
      " Five hundred eighty fourth",
      " Five and hundred eighty-four",
      " Five hundreds and eighty fourth",
    ],
  },
  {
    id: 162,
    question: "Дұрыс жауабын табыңыз    Nancy Zee was a _______ girl",
    key: "beautiful",
    choices: ["beautiful", " scientific", "coloured", "heavy", "early"],
  },
  {
    id: 163,
    question:
      "Cызықтың орнына керекті сөзді қойыңыз    Among the most popular______are basketball, football, hockey, etc",
    key: "sports",
    choices: ["sports", "concert", "books", "movies", "films"],
  },
  {
    id: 164,
    question: "Есімдіктің дұрыс нұсқасын таңда   This child is ______ son",
    key: "my",
    choices: ["my", "he", "i", "you", "your"],
  },
  {
    id: 165,
    question: "Демеуліктің дұрыс нұсқасын таңдаңыз    The train arrives______Rome_____ 4 pm",
    key: "at/at",
    choices: ["at/at", "in/at", "to/in", "near/on", "in/at"],
  },
  {
    id: 166,
    question: "Дұрыс нұсқаны таңдаңыз    When I looked round the door, the baby ______quietly",
    key: "was sleeping",
    choices: ["was sleeping", "slept", "is sleeping", "were sleeping", "sleeped"],
  },
  {
    id: 167,
    question: "Дұрыс нұсқасын табыңыз     The child was glad    There______many animals in the ZOO",
    key: "were",
    choices: ["were", "to be", "are", "is", "the"],
  },
  {
    id: 168,
    question: "Дұрыс нұсқасын табыңыз     1000 books   ",
    key: "one thousand books",
    choices: [
      "one thousand books",
      "ten thousand books",
      "one hundred books",
      "ten thousand books",
      "one thousands book",
    ],
  },
  {
    id: 169,
    question: "I am from New-York",
    key: "Where are you from?",
    choices: [
      "Where are you from?",
      "What is your name?",
      "Where is your father from?",
      "How old are you?",
      "Where is your from?",
    ],
  },
  {
    id: 170,
    question: "What time is it now? - 10-35",
    key: "thirty-five minutes to eleven",
    choices: [
      "thirty-five minutes to eleven",
      "thirty minutes past ten",
      "twenty minutes past ten",
      "twenty-three minutes past ten",
      "half past ten",
    ],
  },
  {
    id: 171,
    question: "Сын есім тудыратын жұрнақты тап    rain",
    key: "y",
    choices: ["y", "iy", "able", "al", "ies"],
  },
  {
    id: 172,
    question: "Cөйлемді аяқта     We keep our food in the__________",
    key: "refrigerator",
    choices: ["refrigerator", "wardrobe", "TV-set", "cupboard", "sofa"],
  },
  {
    id: 173,
    question: "Дұрыс жауапты таңдаңыз    London is the capital of________",
    key: "The UK",
    choices: ["The UK", "Australia", "Northern Ireland", "The USA", "Canada"],
  },
  {
    id: 174,
    question:
      "Бос орынды толықтырыңыз       Kate missed the film last night, because she______work late",
    key: "had to",
    choices: ["had to", "may", "could", "can", "might"],
  },
  {
    id: 175,
    question: "Дұрыс нұсқасын таңдаңыз   How do you say the number 101",
    key: "one hundred and one",
    choices: [
      "one hundred and one",
      "ones hundreds one",
      "one hundreds one",
      "one and one hundred",
      "one thousand one",
    ],
  },
  {
    id: 176,
    question: "Дұрыс нұсқасын таңдаңыз    This is the place ______my uncle lives",
    key: "where",
    choices: ["where", "whom", "which", "who", "whose"],
  },
  {
    id: 177,
    question: "Етістіктің қай формада тұрғанын таңдаңыз  closed",
    key: "Participle II",
    choices: [
      "Participle II",
      "Participle I",
      "Indefinite Infinitive Active",
      "Gerund",
      "Infinitive",
    ],
  },
  {
    id: 178,
    question: "Асты сызылған сөздік сөйлем мүшесін анықтаңыз    We missed our interesting lessons",
    key: "adjective",
    choices: ["adjective", "pronoun", "noun", "verb", "article"],
  },
  {
    id: 179,
    question:
      "Асты сызылған сөздің синонимін тап      She spoke to her English teacher after classes",
    key: "talked",
    choices: ["talked", "discussed", "told", "said", "speaked"],
  },
  {
    id: 180,
    question: "Дұрыс баламаны қойыңыз    Look ______ There is a car coming",
    key: "out",
    choices: ["out", "for", "at", "in", "on"],
  },
  {
    id: 181,
    question: "Сөйлемді толықтырыңыз     A friend in need is _______ indeed",
    key: "a friend",
    choices: ["a friend", "a mother", "a brother", "a doctor", "sister"],
  },
  {
    id: 182,
    question: "large сөзінің күшейтпелі шырайын тап",
    key: "the largest",
    choices: ["the largest", "larger", "the most largest", "the larger", "largiest"],
  },
  {
    id: 183,
    question:
      "Дұрыс жауапты таңдаңыз      I sent a letter two weeks ago and they haven't received it_______",
    key: "yet",
    choices: ["yet", "already", "still", "much", "many"],
  },
  {
    id: 184,
    question:
      "Сәйкес сөзді қойыңыз      The US has two main________ parties – the Democratic Party and the Republic Party",
    key: "political",
    choices: ["political", "civil", "public", "important", "imperial"],
  },
  {
    id: 185,
    question: "Дұрыс баламаны таңдаңыз     Dauren _______his key    He can't get into the house",
    key: "lost",
    choices: ["lost", "loses", "loose", "was lost has", "loses"],
  },
  {
    id: 186,
    question: "Дұрыс нұсқасын табыңыз     She is tired        She_______ not work any more",
    key: "can",
    choices: ["can", "would", "could", "may", "must"],
  },
  {
    id: 187,
    question: "Сұраққа жауап беріңіз     My name is Robert Fulson",
    key: "What is your name?",
    choices: [
      "What is your name?",
      "What is your sister's name?",
      "How old are you?",
      "What's the time?",
      "Where are you from?",
    ],
  },
  {
    id: 188,
    question: "Дұрыс нұсқасын қойыңыз  When I got home, I found that someone________ into my flat",
    key: "had broken",
    choices: ["had broken", "breaks", "break", "is breaking", "breaked"],
  },
  {
    id: 189,
    question:
      "Модаль етістікті пайдаланып сөйлемді аяқтаңыз     Sandra______drive but she hasn't got a car",
    key: "can",
    choices: ["can", "was able to", "are able to", "could", "may"],
  },
  {
    id: 190,
    question: "Бос орынды толықтырыңыз       Her sport car is different_______Kate's",
    key: "from",
    choices: ["from", "so", "like", "as", "look"],
  },
  {
    id: 191,
    question: "busy сөзінің антонимін табыңыз",
    key: "free",
    choices: ["free", "easy", "slightly", "quick", "good"],
  },
  {
    id: 192,
    question:
      "Сәйкес сын есімді пайдаланып сөйлемді аяқтаңыз      He was a bit depressed yesterday but he looks______today",
    key: "happier",
    choices: ["happier", "the happiest", "happiest", "more happy", "hapierst"],
  },
  {
    id: 193,
    question: "Дұрыс нұсқасы таңдаңыз         Lion is the _______ animal",
    key: "strongest",
    choices: ["strongest", "most strongest", "not strong", "stranger", "strongers"],
  },
  {
    id: 194,
    question: "Есімдіктің дұрыс нұсқасын табыңыз     It's easy, you can do it_________",
    key: "yourself",
    choices: ["yourself", "you", "yours", "your", "yous"],
  },
  {
    id: 195,
    question: "Бос орынды дұрыс жауаппен толтыр     My friend likes to eat________",
    key: "fish",
    choices: ["fish", "the fish", "a fishes", "this fish", "fished"],
  },
  {
    id: 196,
    question: "Дұрыс санды таңдаңыз     He lives on 7  floor",
    key: "the seventh",
    choices: ["the seventh", "the sixth", "seven", "the fifth", "a seventh"],
  },
  {
    id: 197,
    question: "Дұрыс жауапты таңдаңыз        Abay ______many poems and quotations",
    key: "wrote",
    choices: ["wrote", "was writing", "used to write", "was written", "were write"],
  },
  {
    id: 198,
    question: "Дұрыс баламаны таңдаңыз       _______some chairs around the table",
    key: "there are",
    choices: ["there are", "there isn't", "there aren't", "there is", "there were"],
  },
  {
    id: 199,
    question: "Дұрыс нұсқаны таңдаңыз    This house _______built in 1946",
    key: "was",
    choices: ["was", "is", "are", "were", "what"],
  },
  {
    id: 200,
    question: "Дұрыс нұсқасын табыңыз  People in Kazakhstan celebrate ________on March 22",
    key: "Nauryz",
    choices: ["Nauryz", "Constitution Day", "Independence Day", "Longest day ", "New year"],
  },
  
];
